#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from keystroke_artifact.common import plot_figure10


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Plot paper Figure 10 from reproduced CSV outputs."
    )
    parser.add_argument(
        "--length-csv",
        type=Path,
        default=REPO_ROOT / "outputs" / "figure10" / "tables" / "figure10_sequence_length_recovery.csv",
        help="CSV generated by the figure10 reproduction step for panel (a).",
    )
    parser.add_argument(
        "--topk-csv",
        type=Path,
        default=REPO_ROOT / "outputs" / "figure10" / "tables" / "figure10_topk_sensitivity.csv",
        help="CSV generated by the figure10 reproduction step for panel (b).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT / "outputs" / "figure10",
        help="Output directory where figures/figure10_performance.{png,pdf} will be written.",
    )
    return parser


def main() -> int:
    args = build_parser().parse_args()
    length_csv = args.length_csv if args.length_csv.is_absolute() else REPO_ROOT / args.length_csv
    topk_csv = args.topk_csv if args.topk_csv.is_absolute() else REPO_ROOT / args.topk_csv
    output_dir = args.output_dir if args.output_dir.is_absolute() else REPO_ROOT / args.output_dir

    missing = [path for path in [length_csv, topk_csv] if not path.exists()]
    if missing:
        print(
            "Missing Figure 10 input CSV(s):\n- " + "\n- ".join(str(path) for path in missing),
            file=sys.stderr,
        )
        return 1

    length_frame = pd.read_csv(length_csv)
    topk_frame = pd.read_csv(topk_csv)
    figure_paths = plot_figure10(length_frame, topk_frame, output_dir)
    print("[artifact-ok] Figure 10 plotted.")
    for kind, path in figure_paths.items():
        print(f"  {kind}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
